### ISSUE TITLE
Implement REST endpoint to return list of categories

### ISSUE THREAD

**Issue by sivaprasadreddy** [leantechstacks/jcart-backoffice-service#2]
Implement REST API **GET- /categories** to return list of categories.

**Sample Response:**
```
[
  {
     id: 1,
     name: 'Animals',
     description: 'Quilling art work for animal toys'
  },
  {
     id: 2,
     name: 'Flowers',
     description: 'Quilling art work for flowers'
  },
  {
     id: 3,
     name: 'Kids',
     description: 'Quilling art work for kids toys'
  }
]
```

**Comment by atomobianco** [comment]
Hi @sivaprasadreddy nice initiative I hope it goes on and I will find time to contribute.

It would be interesting to see (HATEOAS)[http://projects.spring.io/spring-hateoas/] used in the projects. What do you think?

**Comment by sivaprasadreddy** [comment]
@atomobianco Sure. But I am thinking of starting with simple now and add HATEOAS support in next iteration. In this iteration I am focusing on setting up overall flow.
